### ISSUE TITLE
Block WebRTC doesn't work on DuckDuckGo Browser/FFLite browsers

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1015]
### Steps to reproduce

1. Switch-on Stealth Mode
2. On **Block WebRTC** option
3. Chrome browser - the situation is not reproduced
4. But if you check on DuckDuckGo Browser or FirefoxLite. WebRTC is not blocked

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/60882223-17afee80-a250-11e9-88c7-26ca7481fa6c.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/60882313-3ada9e00-a250-11e9-9c2c-c3337d2dcde5.png)

</details>

**Comment by sxgunchenko** [comment]
As the issue is not reproducible on the older android version, where HTTPS filtering of DuckDuckGo Browser is possible, and the browser does not accept our certificate on the latest android versions, it seems like the address leaks with TLS encrypted data.
So, there is nothing we can do in this case.
