### ISSUE TITLE
Add "outbound" HTTPS proxy support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1071]
See here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2984

Once it's done -- add a task to Android repo

**Comment by lancelot-moon** [comment]
HTTPS is one of the requested proxy protocols.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2111

But it's maybe sensitive for Chinese government because encrypted proxy protocols can pass Chinese GFW.

If possible, I'll appreciate that AdGuard gradually supports more other encrypted proxy protocols, ex: SSH, ShadowSocks...etc.

Best Regards.

**Comment by ngorskikh** [comment]
core/pull-requests/1663
