### ISSUE TITLE
Hide Referrer from third-parties function fails in that purpose

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1136]
@Chinaski1 commented on [Mon Sep 23 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3083)

### Issue Details

- **AdGuard version:**
  -  3.3 Nightly 5(25-1.4.138CL)
- **Filtering mode:**
  -  Local VPN
- **Operating system and version:**
  -  Android 9

### Expected Behavior

Function **Hide Referrer from third-parties** should conceal what website we visited.

### Actual Behavior

For example, I try to test in on [amiunique.org/fp](amiunique.org/fp)

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/65425870-b42d6a00-de17-11e9-9dd1-493eedd9a93c.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/65425860-ae378900-de17-11e9-8ebc-e29f3280164f.png)

</details>

---

@d0x360 commented on [Wed Sep 25 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3083#issuecomment-534758219)

This was the issue I reported via the app a couple weeks ago so you probably have my logs.  If you need any more info from me just let me know.

It happened on the nightly but also the stable and beta versions and has in the mighty builds for at least a month as I didn't report immediately in case it got resolved or was a byproduct of something being worked on.

**Comment by sxgunchenko** [comment]
But it's not a third-party request (url and referrer are the same). Why do you expect us to hide it?

**Comment by TheHasagi** [comment]
@sxgunchenko True, thank you. Closed.

**Comment by d0x360** [comment]
Understood but it's still allowing the browser to be uniquely fingerprinted which allows for it's tracking.  Is there no way to hide the referrer from a 1st party?  That information is generally sold allowing for identification is it not?

**Comment by sxgunchenko** [comment]
It does not make much sense. A site won't get any useful information from the fact you came to a page from another page of this site in terms of privacy.

**Comment by d0x360** [comment]
But it shows any site you come from not just if you stay on the same site.
For example if you use a search engine it will show the search engine so I
assume if I came from some other site it would show that...

I suppose i don't see the value in the feature at that point because it
will always show how you got there.

**Comment by sxgunchenko** [comment]
Hide referrer from **thirdp-parties** feature works as intended. 
E.g., if you go to example.org from google.com, we hide from example.org the fact you came from another site.
On the other side, if you go to example.org/page from example.org, we won't do it, because it's not a third-party request.
The second case is exactly what happened with amiunique.org/fp, and that's not an issue.

**Comment by d0x360** [comment]
Ok that makes more sense.  Thanks for the explanation
