### ISSUE TITLE
Unable to connect to NordVPN servers an outbound proxy

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1144]
### Issue Details

- **AdGuard version:**
  -  3.3.6(42-1.4.138cl)
- **Filtering mode:**
  -  VPN
- **Device:**
  -  ASUS (ZB602KL)
- **Operating system and version:**
  -  Android 9
- **Root access:**
  -  No

### Expected Behavior

Following the instructions from the [knowledge base](https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy) configure AdGuard proxy.

### Actual Behavior

After configuration, you cannot connect to any of the servers.
*DNS filtering is disabled*.

<details><summary>Screenshot:</summary>

![image](https://uploads.adguard.com/TheHasagiqpzsv.jpg)

</details>

**Comment by CodeVerse** [comment]
Hi there!

I'm the initial user that reported this issue to the AdGuard support team.

I'd really like to use both AdGuard and NordVPN at the same time on Android, and currently I can only have one or the other active due to the DNS issue.  Is there any type of workaround that I can do on my end?  Thank you.

**Comment by ameshkov** [comment]
@CodeVerse hi! please check that the server you're trying to use is not "obfuscated"

**Comment by CodeVerse** [comment]
Thank you for the response.  Unfortunately all servers I have attempted to connect to that don't show as 'obfuscated', such as 'us3119.nordvpn.com'.  A list of available servers and protocols for NordVPN can be obtained using their tool here: 'https://nordvpn.com/servers/tools/'

The issue still persists, even after checking several different servers today.  I'm actually surprised this isn't more of a wide-spread issue, assuming that most AdGuard users would be interested in keeping their browsing secure using a VPN provider.  Maybe I'm the only one in thousands of users that uses both?

**Comment by TheHasagi** [comment]
@CodeVerse 

Hello!

What version do you use?

Can you check with the latest [nightly](https://agrd.io/android_nightly)?

By the way, here is my response from proxy you provided:

<details>

![img](https://uploads.adguard.com/TheHasagieeexz.jpg)

</details>

**Comment by CodeVerse** [comment]
Hi @Alexanser,

Thanks, attempted ghe latest nightly with no luck.  Ghe build I was
previously using was v3.2.150 (1.4.138cl).

I do receive the 'Proxy is working' message as well when checking the
connection, however after restarting the vpn in proxy mode then attempting
to visit a site in Google Chrome is received with the error
'err_address_unreachable'.  Im addition, apps like WhatsApp fail to
communicate with thier servers properly.

**Comment by ameshkov** [comment]
@CodeVerse 
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Open AdGuard -> Settings -> Advanced -> Set "Logging level" to "Record everything". It's desirable to close all background apps that don't concern the problem beforehand.
2. Reproduce the issue and set the logging level back to "Default".
3. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
4. Open AdGuard -> Settings -> Advanced -> Export Logs
5. Send it to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by CodeVerse** [comment]
@ameshkov 
Will do, I'll update this post with the provided logs by tomorrow.  Thank you!

**Comment by ameshkov** [comment]
Logs are in the private nextcloud.

Here's the error in the log that corresponds to the attempt to open test.com:
```
18:05:31.107 [Thread-167] DEBUG Native.AGAndroidProxyServer - operator(): [id=1000032] Error connecting to 69.172.200.235:80. DNS error: 4(non-recoverable failure in name resolution)
```

**Comment by Chinaski1** [comment]
It looks like another user faced an issue like this. 
The device cannot access the network when using the outbound proxy via Wi/Fi
[AdGuard Forum](https://forum.adguard.com/index.php?threads/nordvpn-outbound-proxy.36268/#post-192394)
The archive is added to NCloud

**Comment by akmLaVx** [comment]
User 2128654 reports the issue also affects Orbot intergration as well.

**Comment by vshlobinag** [comment]
Add logging core/pull-requests/1647

**Comment by ameshkov** [comment]
@CodeVerse 

We've added more logging to AdGuard and it should help us figure what's wrong.

Could you please try this build?
https://up.agrd.eu/adguard-cl1.5.152.apk

Please record the full log again and send it to us.

**Comment by CodeVerse** [comment]
@ameshkov 

Requested logs have been submitted to devteam@adguard.com

Here is a log of my actions:

15:30:02 - Turned on Logging (AdGuard service enabled)
15:30:33 - Searched for 'test' via default search engine on Google (DuckDuckGo) with successful access to site.
15:31:03 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
15:31:30 - Attempted to access site (via Google Chrome) 'test.com' with 'err_connection_reset'
15:31:46 - Diabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
15:32:25 - Attempted to access site (via Google Chrome) 'test.com' with successful connection to site.
15:32:37 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
15:32:54 - Attempted to access site (via Google Chrome) 'hello.com', with response 'err_address_unreachable'
15:33:07 - Disabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
15:33:22 - Attempted to access site (via Google Chrome) 'hello.com', with successful connection to site.

I'm happy to help out any way I can, if needed in the future.

**Comment by ameshkov** [comment]
@CodeVerse quick question: does DNS filtering work properly for you if you choose the "System default" server instead of the custom server? Without proxy, just DNS filtering.

 It suspect that AG might be detecting wrong system default DNS server and that's what's breaking everything.

**Comment by sfionov** [comment]
@CodeVerse Can you please try this special build with additional DNS logging, and send to us full log again?
https://uploads.adguard.com/adguard-3.3-nightly-31-dns-debug.apk

**Comment by CodeVerse** [comment]
@ameshkov - Yes it appears that the DNS filtering works properly for the default system VPN with no proxy.

@sfionov - I've sent the requested logs.  Here is a list of log of my actions:

16:40:10 - Turned on Logging (AdGuard service enabled)
16:40:32 - Searched for 'test' via default search engine on Google (DuckDuckGo) with successful access to site.
16:40:48 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
16:41:16 - Attempted to access site (via Google Chrome) 'test.com' with successful connection to site.
16:41:36 - Diabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
16:41:57 - Attempted to access site (via Google Chrome) 'test.com' with successful connection to site.
16:42:18 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
16:42:47 - Attempted to access site (via Google Chrome) 'hello.com', with response 'err_address_unreachable'
16:43:27 - Attempted to access site (via Google Chrome) 'bing.com', with response 'err_address_unreachable'
16:44:00 - Disabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
16:44:17 - Attempted to access site (via Google Chrome) 'hello.com', with successful connection to site.
16:44:49 - Attempted to access site (via Google Chrome) 'bing.com', with successful connection to site.

Note that after reading some of the additional comments on this thread, I tested the proxy via cellular connections (not wifi), and it appeared to work properly (no logs created).  All of my testing up until this point, including this series of tests are all via Wifi.

**Comment by ameshkov** [comment]
@CodeVerse thank you!

@sfionov please find the logs in the NextCloud - `adguard_logs_3.3.200_1412_164510`. So it seems that issue is on the CoreLibs side, evdns specifically.

**Comment by sfionov** [comment]
@CodeVerse 
We still can't reproduce on our hardware, your help is needed!
Can you please try this build and send us debug logs? We added even more DNS logging into this build, hope this will allow us to fix the problem.
https://uploads.adguard.com/adguard-3.3-nightly-36-dns-debug-2.apk

**Comment by CodeVerse** [comment]
@sfionov 
All set, the logs have been sent.  Happy Holidays!

Here is a log of my actions:
11:48:08 - Turned on Logging (AdGuard service enabled)
11:48:37 - Searched for 'test' via default search engine on Google (DuckDuckGo) with successful access to site.
11:48:50 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:50:06 - Attempted to access site (via Google Chrome) 'bing.com' with 'err_address_unreachable'
11:50:53 - Diabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:51:07 - Attempted to access site (via Google Chrome) 'bing.com' with successful connection to site.
11:51:26 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:51:49 - Attempted to access site (via Google Chrome) 'hello.com', with response 'err_address_unreachable'
11:52:01 - Disabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:52:10 - Attempted to access site (via Google Chrome) 'hello.com', with successful connection to site.
11:52:23 - Turned on AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:52:54 - Attempted to access site (via Google Chrome) 'meow.com', with response 'err_address_unreachable'
11:53:29 - Disabled AdGuard via Proxy (us3119.nordvpn.com, port 1080, socks5)
11:53:52 - Attempted to access site (via Google Chrome) 'meow.com', with successful connection to site.

Note that to ensure reproduction, you will want to visit a domain that was not previously visited before enabling the proxy, otherwise, it appears that the resolution seems to work randomly, again probably due to DNS caching.

**Comment by ameshkov** [comment]
@sfionov look for `adguard_logs_3.3.228_2712_115440.zip` in NextCloud

**Comment by Serdans** [comment]
Same issue here on certain public WiFi networks. Do you need more logs?

**Comment by Chinaski1** [comment]
let’s do the following:
- AdGuard > Settings > Advanced > Logging Level > Record All.
- Reproduce your issue.
- Note the time the error occurred and let us know.
- Don’t forget to return to the default logging level.
- Logs can be sent to me at PM or on devteam@adguard.com

**Comment by ameshkov** [comment]
@Serdans are you on the latest nightly version?

@CodeVerse could you please try the latest nightly version? We've changed the DNS library so I hope the issue might be gone

**Comment by CodeVerse** [comment]
@ameshkov tested out the latest nightly and it seems to fix the issue for me, all browsing via Wifi via NordVPN proxy works properly.  Thank you!

**Comment by Serdans** [comment]
Yup seems to be working on the latest nightly @ameshkov. 👍
