### ISSUE TITLE
Consider using Referrer Policy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#135]
https://www.w3.org/TR/referrer-policy/

Relevant discussion:
https://forum.adguard.com/index.php?threads/sources-of-some-requests-were-not-identified.13260/

**Comment by sfionov** [comment]
I think here is an important thing: if policy is changed by us, it must be applied on AdGuard's side because site authors designed it to not to leak referrers.

**Comment by sfionov** [comment]
Here's some sites that may be affected by Referrer-Policy:

https://github.com/AdguardTeam/Scriptlets/issues/196

**Comment by ngorskikh** [comment]
@ameshkov 

What if we added a new basic rule modifier like this:
```
||example.org^$referrerpolicy=one|two|three
```

Which, in this case, would replace all `Referrer-Policy` headers (or add one, if none are present), and replace the content of `<meta name="referrer">` tag with the policy `one,two,three`.

Exceptions could work like this:
```
||example.org^$referrerpolicy=one|two|three

! Remove the policies "one" and "two" from the patched value
@@||example.org^$referrerpolicy=one|two

! Completely disable referrerpolicy rules on matching requests
@@||example.org^$referrerpolicy

! Completely disable the $referrerpolicy=one|two|three rule
@@||example.org^$referrerpolicy=one|two|three 
```

Since the referrer policy is sensitive to order (the latest policy understood by the browser is applied), and we can't preserve the order of rules when parsing them, we would have to introduce a gotcha such as "if multiple rules match the same request, only one of them is applied, unspecified which one".

**Comment by ngorskikh** [comment]
Then I propose that simply
```
||example.org^$referrerpolicy=one\,two\,three
```
should replace the policy with the unescaped value of the modifier, and exceptions should work like this:
```
! Disable the rule with the modifier value equal to `one\,two\,three`
@@||example.org^$referrerpolicy=one\,two\,three

! Disable all rules for matching requests
@@||example.org^$referrerpolicy
```

**Comment by sfionov** [comment]
Looks good for me
