### ISSUE TITLE
Add possibility to use document modifier in $replace rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1439]
At the moment if we want to use a `$replace` rule only for `document`, we need to use for example something like this:
`||example.org^$replace=/h1/mark/,~script,~stylesheet,~xmlhttprequest,~other`
I think that it would be nice to have possibility to use just a `document` modifier in case like that.
`||example.org^$replace=/h1/mark/,document`

**Comment by ameshkov** [comment]
We definitely need a modifier for HTML document content type which is indeed missing right now.

And not just for $replace rules, there're more cases when it may be useful.

**Comment by contribucious** [comment]
Hello,
&nbsp;

Oh! I see… :eyes:

That would therefore explain the choice of a `$~script` rule by @Alex-302 concerning `tf1.fr` (see [my comment](https://github.com/AdguardTeam/AdguardFilters/issues/77931#issuecomment-821383943)), instead of `$document`. Although this could have been optimized in `$~script,~stylesheet,~xmlhttprequest,~other` though (long, admittedly! :wink:).
&nbsp;

<details>
<summary>Read more …</summary>

### Details

Being under Linux _(using the Firefox browser extension)_ and seeing this in the KB about [$replace](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier):
```
Compatibility with different versions of AdGuard.
These rules are supported by AdGuard for Windows, Mac, Android and by the AdGuard's Firefox add-on.
```
…I actually didn't think that my suggested `$document` rule would not be supported in products using **CoreLibs** (Windows, macOS, Android). Unlike the Firefox browser extension where this seems to be the case according to the AdGuard "Filtering log" window (only requests listed with an "HTML" type had this rule applied during my tests, as expected).

:safety_pin: I should have actually written my rule in the long format, consequently.
:safety_pin: _Anyway, for this specific case, the more compatible alternative solution (scriptlet) was finally chosen._
&nbsp;

### :arrow_right: Suggestion

:warning: However, according to my tests, the Firefox browser extension does not currently support the cumulative format `$document,subdocument,replace=[…]` _(see the TF1 issue mentioned above, where the use case is for a replacement in the standard or embedded version of the "documents")_ and it might be good to have this support both in **CoreLibs** and in the Firefox browser extension _(for the `$replace` case)_ or even in other browser extensions too _(for other cases, as mentioned by @ameshkov)_ in my opinion, if it is feasible. :thumbsup:
</details>

**Comment by ameshkov** [comment]
Oh, indeed, we should also file a task to https://github.com/AdguardTeam/tsurlfilter so that this change was  made to browser extensions as well.

**Comment by contribucious** [comment]
@ameshkov :thumbsup:
&nbsp;

:arrow_right: I reworked my **Suggestion** paragraph but so, in summary:
&nbsp;

## Current situation:

### CoreLibs
`$document,replace=[…]` :heavy_multiplication_x:
`$subdocument,replace=[…]` :heavy_multiplication_x:
`$document,subdocument,replace=[…]` :heavy_multiplication_x:

### TSUrlFilter _(in Firefox)_
`$document,replace=[…]` :heavy_check_mark: _(tested with success)_
`$subdocument,replace=[…]` :heavy_check_mark: _(tested with success)_
`$document,subdocument,replace=[…]` :heavy_multiplication_x:
&nbsp;

## Ideal situation:

### CoreLibs + TSUrlFilter*
`$document,replace=[…]` :heavy_check_mark:
`$subdocument,replace=[…]` :heavy_check_mark:
`$document,subdocument,replace=[…]` :heavy_check_mark:

##### * _(In Firefox only for the `$replace` case, but in all other browsers also otherwise.)_

**Comment by contribucious** [comment]
Yayy! Kudos to the team! :wink:
