### ISSUE TITLE
Syntax for removing elements from JSON responses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1447]
We often face issues when we need to modify JSON strings. Usually, we use $replace for that, but it is FAR from ideal.

What we really need is a new modifier similar to `$replace` that will work with JSON's specifically.

Now, the question is what syntax should we use that can be understood and can be tested/debugged as easy as a regular expression.

I suggest using `jq` syntax for that: https://stedolan.github.io/jq/

Here's why:
1. `jq` is written in C under a permissive license and we can use it as a library: https://github.com/stedolan/jq/blob/master/COPYING 
2. `jq` can be used in conjunction with `curl` to test the jq expressions: https://stedolan.github.io/jq/tutorial/
3. `jq` expressions can also be tested online: https://jqplay.org/

@sfionov @sxgunchenko any ideas on what syntax of this modifier could be?
@AdguardTeam/filters-maintainers what do you think about this idea?

**edit**: relevant: https://github.com/AdguardTeam/Scriptlets/issues/183#issuecomment-1019960905

Maybe using jq is not that sane, we'd better find something that has implementations in both JS and C/C++

**Comment by ngorskikh** [comment]
@ameshkov For the JS side of things, there are at least two possibilities:
* Use a native JavaScript implementation, e.g.: https://github.com/mwh/jqjs
* Compile JQ to WebAssembly, e.g. like they did here: https://github.com/fiatjaf/jq-web

**Comment by sfionov** [comment]
I think that we should provide a full list of supported functions, if it is possible. For example, we definitely will not support `halt` and `halt_error` :)

**Comment by ngorskikh** [comment]
@sfionov I didn't want to commit to a specific list until we have the JavaScript implementation. Also, we might remove something during further testing :)

By the way, `halt` and `halt_error` are not a problem: they halt the JQ program, not the whole AdGuard :)

**Comment by ngorskikh** [comment]
JMESPath is 18K minified: https://github.com/jmespath/jmespath.js/blob/master/artifacts/jmespath.min.js

Probably still too fat :)

**Comment by ngorskikh** [comment]
Btw, it looks like WebAssembly should be allowed in manifest v3 extensions: https://bugs.chromium.org/p/chromium/issues/detail?id=1173354#c60
there are reports that it works in Chrome Canary

**Comment by ngorskikh** [comment]
@ameshkov I've been thinking: if we really want an extremely small implementation, then isn't it gonna be simpler to just extend the existing `json-prune` scriptlet by addressing the issues described in [https://github.com/AdguardTeam/Scriptlets/issues/183](https://github.com/AdguardTeam/Scriptlets/issues/183)?

I presume, we'll still want to implement the same functionality as a native CoreLibs rule?
If not, then let the Scriptlet guys figure it out :)

If yes, then how about extending the `json-prune` syntax so that each component of the path can contain a conditional, something like this:
```
recs_group.[] some-conditional(args).tiles.[].[] has-key("ad_origin")
```
or even a conditional that itself accepts a path expression (this one will be a pain to parse):
```
recs_group.[] some-conditional(args).tiles.[].[] has(type value-equals("ad"))
```
This should solve the two issues from [https://github.com/AdguardTeam/Scriptlets/issues/183](https://github.com/AdguardTeam/Scriptlets/issues/183) and shouldn't be too hard to implement in both the scriptlet and CoreLibs.

The problem I see with this solution is that we'll most probably want more and more features down the line, which will be increasingly more difficult to implement. While with `jq` we can already do pretty much anything we want with a json document, without any additional work on our side :)

**Comment by ngorskikh** [comment]
@ameshkov How about this for a rule spec:

### `$jsonprune` modifier

`$jsonprune` rules modify the JSON response of a matching request by removing JSON items that match a modified (see below) 
[JSONPath](https://goessner.net/articles/JsonPath/) expression. They do not modify responses which are not valid JSON.

### Syntax
* `||example.org^$jsonprune=expression` – remove items that match the modified JSONPath expesssion `expression` from the response.

Due to the way rule parsing works, the characters `$` and `,` must be escaped with `\` inside `expression`.

The modified JSONPath syntax has the following differences from the original:
1. Script expressions are not supported.
2. The supported filter expressions are:
2.1. `?(has <key>)` -- true if the current object has the specified key.
2.2. `?(key-eq <key> <value>)` -- true if the current object has the specified key,
                                  and its value is equal to the specified value.
2.3. `?(key-contains <key> <value>)` -- true if the specified value is a substring
                                        of the specified key of the current object.
3. Whitespace outside of double- or single-quoted strings has no meaning.
4. Both double- and single-quoted strings can be used.
5. Expressions ending with `..` are not supported.
6. Multiple array slices can be specified in square brackets.

### Exceptions

Basic URL exceptions shall not disable `$jsonprune` rules. They can be disabled as described below:
* `@@||example.org^$jsonprune` – disable all `$jsonprune` rules for responses from URLs matching `||example.org^`.
* `@@||example.org^$jsonprune=text` – disable all `$jsonprune` rules with the value of the `jsonprune` modifier equal to `text` for responses from URLs matching `||example.org^`.
* `$jsonprune` rules can also be disabled by `$document`, `$content` and `$urlblock` exception rules.

### Restrictions
* `$jsonprune` rules are only allowed in trusted filters.
* `$jsonprune` rules are not compatible with any other modifiers except `$domain`, `$third-party`, `$app`, `$important`, `$match-case`, and `$xmlhttprequest`.
* `$jsonprune` rules do not apply if the size of the original response is more than 3 MB.

### Notes
* When multiple `$jsonprune` rules match the same request, they are sorted in lexicographical order,
the first rule is applied to the original response, and each of the remaining rules is applied
to the result of applying the previous one.

### Examples
* `||example.org^$jsonprune=\$..[one\, "two three"]` — remove all occurences of the keys "one" and "two three" anywhere in the JSON document.
* `||example.org^$jsonprune=\$.a[?(has ad_origin)]` – remove all children of `a` that have an `ad_origin` key.
* `||example.org^$jsonprune=\$.*.*[?(key-eq 'Some key' 'Some value')]` – remove all items that are at nesting level 3 and have a property "Some key" equal to "Some value".

**Comment by ameshkov** [comment]
Looks good. One more thing to add to Notes - web app to debug JSONPath expressions.

**Comment by ameshkov** [comment]
> $jsonprune rules are only allowed in trusted filters.

I actually don't think we need this limitation for `$jsonprune`.

**Comment by ameshkov** [comment]
$replace is much more powerful though, `$jsonprune` only allows removing elements, not replacing it.

**Comment by ngorskikh** [comment]
Hypothetically, a malicius filter could remove some kind of hash/signature/checksum and then the client would not check it, and could potentially load and execute a malicius resource. Seems far fetched, ofc, but one can not be too careful.
Then there's a possibility for just pure vandalism, breaking sites in subtle ways by removing certain JSON data. Although, something like this could also be done with basic URL filters.
Alright, I'll remove the requirement, but I have voiced my concerns for the record :)
