### ISSUE TITLE
Rules with $removeparam and regex which contains `|` don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1453]
It seems that if `$removeparam` rule contains regex with `|` then it doesn't work and can't be added.

Steps to reproduce:
1. Try to add this rule:
`||example.com^$removeparam=/abc|xyz/`

It can't be added:
![image](https://user-images.githubusercontent.com/29142494/118396846-ae6e4300-b651-11eb-9e8e-8d81636c78c5.png)

Even if it will be added in a custom filter then it doesn't work.
Test link - http://example.com/page?abc=test

**Comment by krystian3w** [comment]
Other:

`||google.*/search$queryprune=/^(bih|biw|client|dpr|ei|gs_lcp|iflsig|oq|sa|sclient|source|spell|uact|ved)/,domain=google.*`

**Comment by ameshkov** [comment]
Guys, there's a disrepancy with CoreLibs versions.

The current stable AdGuard versions use CoreLibs v1.7 which used a little bit different syntax of $removeparam (it was simply `$removeparam=bih|biw|client`).

CoreLibs v1.8 implemented the updated syntax which you're trying to use, but this new version has not been released yet.

We're planning to push it to all AG platforms in the coming two months. For the time being, please use the simple syntax ($removeparam=paramname) so that it was compatible with both v1.7 and v1.8.

**Comment by AdamWr** [comment]
Okay, thank you for your reply :)

By the way, I think that it would be nice to add these kind of information also to documentation, because there are some examples, like for instance this one - `||example.com^$removeparam=/^(yclid|fbclid)=/` which do not work with current version, so it is a bit misleading.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam-modifier#:~:text=||example.com^$removeparam=/^(yclid|fbclid)=/
