### ISSUE TITLE
Exclusion with `~third-party` modifier does not unblock when element removed from HTML

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1488]
### Steps to reproduce
1. Disable all filters and add to user rules:
`/back-to-top.`
2. Go to phonearena.com

### Actual behavior - site is broken, because CSS file removed from HTML(it is ok)
`https://s-cdn.phonearena.com?b=css&1627630390806&f=pages/home.css,versions/widgets/heading-deals.css,versions/widgets/back-to-top.css,widgets/header.css,widgets/widget-articles-grid.css,widgets/featured-stories.css,widgets/widget-grid.css,widgets/sidebar-subscription-home.css` (yes, there are no `/` after TLD)

When you try to unblock it by following rule, it is still blocked
`@@||s-cdn.phonearena.com?b=css&*/back-to-top.css$~third-party`
After removing modifier element is unblocked.

Reproduced with AdGuard for Android 4.0 n19 (60-1.8.141cl)

**Comment by ngorskikh** [comment]
I took a look at the code, and it looks to me like intended behaviour: `$~third-party` requires that the domain of the URL being checked and the referrer's domain are exactly the same. In this case, the referrer is `www.phonearena.com` while the link's domain is `s-cdn.phonearena.com`, so the exception rule doesn't apply.
Also, `$~third-party` rules currently do not apply if the referrer is empty for some reason.
Summoning the architects: @sxgunchenko @ameshkov

**Comment by sxgunchenko** [comment]
Hm... According to the specs https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#third-party, this looks like a bug. We should not treat requests to subdomains as third-party :(

**Comment by ngorskikh** [comment]
Hmm, it looks like subdomains should be considered when determining the `party`-ness of the request: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#third-party
Still, in this case `www.phonearena.com` wouldn't match `s-cdn.phonearena.com`, should we perhaps ignore the `www.` prefix?

**Comment by ameshkov** [comment]
Here's the logic of how we determine third-party*ness*:

1. Extract the registered domain name (eTLD+1) from URL1
2.Extract the registered domain name (eTLD+1) from URL2
3. Compare it. If it's different, the URLs are third-party to each other.

**Comment by ngorskikh** [comment]
Ok, the third-first-party-domain matching is fixed. 
We've got another problem, however:

Suppose we have a link in a document:
```
<link href="example.org?abc=123"/>
``` 

The link is fetched with a request:
```
GET /?abc=123 HTTP/1.1
    ^- this slash is always inserted by the user agent
Host: example.org
```

That's because, according to RFC 7230:
>If the target URI's path component is   empty, the client MUST send "/" as the path within the origin-form of   request-target.

When reconstructing a full URL to match against the rules, we can't determine if the `/` was originally present in the URL, or was inserted by the user agent. 

This means that a rule ```@@||example.org?abc=123``` will match the `<link>` tag, but not the request, while a rule ```@@||example.org/?abc=123``` will match the request, but not the link tag.

We could omit the `/` if the path is empty when reconstructing the URL, but then there are plenty of rules like `example.org/?something`, which would break. 

It seems this problem can only be solved on a case-by-case basis with multiple rules or one regex rule.

**Comment by ameshkov** [comment]
@ngorskikh what about this one? `@@||example.org^?abc=123`

**Comment by ngorskikh** [comment]
@ameshkov The `^` would match any unreserved URL character + some other chars, but won't match an absence of character, so still wouldn't work.

**Comment by ngorskikh** [comment]
`^?` now matches a separator followed by `?` as well as just `?`, core/pull-requests/2492
