### ISSUE TITLE
ECH-enabled client

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1565]
AdGuard should be able to work as a ECH-client. This task is a pre-requisite for #553 

This means that regardless of what happens on the client-side (whether it uses ECH or not), we should be able to encrypt SNI using ECH.

This feature must be exposed in AdGuard apps via a low-level setting.

**Comment by Rtizer-9** [comment]
Since ECH is now a ietf standard and Firefox, chrome as well as edge are supporting and working without any issues with ECH unlike ESNI; is there any update on this?

In my current testing chrome under android is working fine with ECH enabled and adguard routing but if I enable https filtering then ECH gets disabled.

Although there were mentions of android webview supporting it I can't see any ech/dns flag in canary webview.

As mentioned in the title, Adguard should be able to encrypt sni on its own given that it already has control over dns so that all the apps routing through it should have ECH enabled.

Currently all other apps depending on webview can't make use of ECH irrespective of whether ag routes them or not.

**Comment by Rtizer-9** [comment]
Since ECH is now a ietf standard and Firefox, chrome as well as edge are supporting and working without any issues with ECH unlike ESNI; is there any update on this?

In my current testing chrome under android is working fine with ECH enabled and adguard routing but if I enable https filtering then ECH gets disabled.

Although there were mentions of android webview supporting it I can't see any ech/dns flag in canary webview.

As mentioned in the title, Adguard should be able to encrypt sni on its own given that it already has control over dns so that all the apps routing through it should have ECH enabled.

Currently all other apps depending on webview can't make use of ECH irrespective of whether ag routes them or not.
