### ISSUE TITLE
Problem with multiple site certificates

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1700]
Странная ситуация с сертификатами и отсутствием из-за этого фильтрации на сайте https://santa.by.
Указанная проблема отсутствует при заходе по веб-адресу с префиксом https://www.santa.by.

<details><summary>screenshot:</summary>

![image](https://user-images.githubusercontent.com/50718960/204794739-37dc0f90-ce28-4483-9234-d2e5afa7066e.png)
</details>

**Comment by zubrRB** [comment]
Ошибку устраняет прописывание в пользовательском фильтре исключения защиты от DPI: `@@||santa.by^$stealth=dpi`

**Comment by ngorskikh** [comment]
DPI protection and MITM are not related in any way. The site does indeed break when using DPI, so the exclusion rule is the correct solution.

As for the discrepancy between the certificates displayed by AdGuard and Chrome, this might be due to Chrome showing outdated info. As clearly seen on the screenshot, MITM and filtering are actually enabled while Chrome shows an incorrect cert. When I was testing this issue a few weeks ago, the site Was sending different certificates at different times. That might have thrown Chrome off, while AdGuard was showing the correct original cert at all times. In any case, the issue does not seem to reproduce now.

**Comment by zubrRB** [comment]
Сейчас тоже несколько ломает DPI, но фильтруется, а тогда на скриншоте не работала фильтрация (видна плашка внизу).
