### ISSUE TITLE
podhale24.pl - corrupted encoding

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1720]
Steps to reproduce
1. Add this rule to user rules (or just disable all modules):
```adblock
podhale24.pl$@$script[tag-content="fbevents.js"][max-length="500"]
```
2. Go to - [https://podhale24.pl/aktualnosci/artykul/88796/30_punktow_i_30_tysiecy_grzywny_za_jazde_tunelem_pod_prad_video.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpodhale24.pl%2Faktualnosci%2Fartykul%2F88796%2F30_punktow_i_30_tysiecy_grzywny_za_jazde_tunelem_pod_prad_video.html)
3. Some characters are displayed incorrectly

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/212656159-340bd434-6827-48b4-a465-2bea48dfbe79.png)

</details>

AdGuard for Windows version 7.12 nightly 6 (build 4152, CL 1.10.182)

**Comment by AdamWr** [comment]
It looks like that it can be fixed by adding this rule:
```adblock
podhale24.pl$$script[tag-content="fbevents.js"][max-length="500"]
```
to user rules, so I'm not sure if it's CoreLibs issue or not (though, it happens even with all modules disabled).

I will add it to Base filter, so before checking it out, please add this rule:
```adblock
podhale24.pl$@$script[tag-content="fbevents.js"][max-length="500"]
```
to user rules (I will also update first comment).

**Comment by zubrRB** [comment]
Test version 7.12 nightly 7 (build 4156, CL 1.10.188)

<details><summary>Screenshot:</summary>

![3](https://user-images.githubusercontent.com/50718960/212660088-de8783c7-e0f9-4ee4-a4b5-b6f2d24e526a.png)
</details><br/>

**Comment by grumaxxx** [comment]
@AdamWr Seems this problem appears aftrer injecting content script, cause if we prevent injecting with rule

```adblock
@@||podhale24.pl$jsinject,content,elemhide,extension
```
everything is ok.

@slavaleleka please, take a look.

**Comment by sfionov** [comment]
@grumaxxx Actually your screen doesn't look ok - there are a lot of broken letters.

**Comment by grumaxxx** [comment]
@sfionov Yes, my screenshot with errors, added to show that the encoding breaks in different ways.

**Comment by sfionov** [comment]
Injection of userscript doesn't break encoding BTW.

I checked `document.inputEncoding` of broken page - it is `ISO-8859-2`
Original page has encoding `utf-8`.

Seems that some manipulations was performed by content-script which triggered detection of page encoding.
And following `<meta charset=utf-8>` was not applied because page encoding was already chosen.

**Comment by sfionov** [comment]
@AdamWr @grumaxxx I dug into this and determined the problem.

The chrome looks up only first 1024 bytes for start tag of `<meta charset` or `<meta http-equiv="content-type"`

At least `<meta http-equiv="c` is required to be placed in first 1024 bytes.

When we inject our scripts, we may shift this meta tag, and this condition is not met. Then Chrome incorrectly autodetects page encoding as Latin-2.

I think that changing inject algorithm is not a good idea because it affects any site, so a solution is rule like yours (deleting the script that is anyway blocked), or to inject charset after head:

```
||podhale24.pl$replace=/head>/head><meta charset="utf-8">/
```

**Comment by AdamWr** [comment]
Okay, I suppose that the `$replace` rule is a preferable solution in this case, so I will add it.
I guess that it can be closed.

Thank you for checking it out.

**Comment by AdamWr** [comment]
Similar cases - https://github.com/AdguardTeam/AdguardFilters/issues/176738 and https://github.com/AdguardTeam/CoreLibs/issues/188

**Comment by zloyden** [comment]
Similar case https://github.com/AdguardTeam/AdguardFilters/issues/186870.

**Comment by Yuki2718** [comment]
Another one `https://x.com/kairi_005/status/1924467480908693995`
