### ISSUE TITLE
The macOS app Filtering Log Is Badly Designed.

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/CoreLibs#1784]
The design of Adguard's Filtering Log doesn't recognise when parts of a webwpage are blocked by Cosmetic/Element hiding rules, they can be in a subscribed to Filter Lister or a Custom User Created Rule.

This badly designed Filtering Log makes it extremely difficult to determine what is blocking parts of a webpage.

This should NOT be the case, ALL BLOCKED ITEMS should be reported.

This is in a fact a Technical Issue which is created by the badly designed Filtering Logs.

Adguard have stubbornly refused to acknowledge there is a problem created by the Filtering Logs.

This was raised 5 years ago on the Github Forums

Adguard have done ABSOLUTELY NOTHING TO FIX THIS.

With various other ad blockers such as ublock Origin, the filtering logs do clearly show when a Cosmetic or User/Custom rule is in effect.

When Blocked Items are NOT REPORTED AT ALL, do you understand that this makes discovering the source of a webpage problem an extremely time consuming, difficult and painstaking process.

To discover the source of the problem I literally had to spend several hours of my valuable time disabling each and every single Adguard function one at a time and then reloading the webpage until I discovered the source of the problem.

It is absolutely disgusting and quite shameful that after 5 very, very long years Adguard has still done absolutely NOTHING about this.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/CoreLibs/issues/180

This is generally a very complicated thing to implement in a network-level content filter and that's why it's not the top priority. In this regard browser extensions have a much easier work to do as they have a simple way to communicate between a browser tab and the extension itself. Network-level content filtering implies that the filtering is done **outside** the browser which gives us many obvious advantages, but also some disadvantages are there too.
