### ISSUE TITLE
Show cosmetic rules in the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#180]
The idea is to collect cosmetic rules and show them in the filtering log.

Here's how it can be done:
1. We need to add some kind of a "cosmetic rules hits collector" to the content script.
2. It must be disabled by default (unless filtering log is opened).
3. Once it is opened, hits collector should start scanning DOM elements and detect elements hidden by AG.

For scriptlet rules we could rely on `hit()` calls.

The task is partly implemented since CoreLibs v1.12, but there're issues that need to be resolved before we announce it publicly.

* [ ] Extended CSS rules are not reported to console (try `example.org#?#body`)
* [ ] Add a log entry that explains that the content script is in verbose mode:

  ```
  console.log('[AdGuard] AdGuard operates in verbose mode due to Filtering Log being open. It will print more information to console.')
  ```

* [ ] Improve the content script logging format so that it was possible to navigate directly to the DOM element that was affected by the rule:

  ```
  console.log(
      `[AdGuard] Filter ${filterID}: %c${ruleText}%c: `, 
      'font-weight: bold;', // style for ${ruleText}
      '', // reset style
      element
  );
  ```

* [ ] Improve the way scriptlets report hits, instead of this:

  ```
          prefix += `#%#//scriptlet('${source.name}', '${source.args.join(', ')}')`;
  
          log(`${prefix} trace start`);
          if (trace) {
              trace();
          }
          log(`${prefix} trace end`);
  ```

  Use something like this:
  
  ```
          label = `[AdGuard] ${prefix}#%#//scriptlet('${source.name}', '${source.args.join(', ')}')`;
  
          if (trace) {
              trace(label);
          }
  ```

**Comment by jputting** [comment]
I am still extremely unhappy with the truly dreadful customer support provided by Adguard to customers whom have a full paid for Personal Lifetime License.

For the record, I am not in any way asking for an enhancement to Adguard.

This issue I have reported is a Technical Fault with the Adguard Filtering Logs NOT recognizing blocked items.

This Technical Support issue has been incorrectly categorised as it is very clearly NOT a request for an enhancement.

Please deal with this Technical Support issue urgently as when the Adguard Filter Log doesn't recognise that items are blocked it then becomes a very, very long drawn out and difficult process to discover what is causing an issue with a webpage.

Once again your so called Technical Support has failed dismally, it is unacceptable that Adguard Customers should have to endure such extremely bad Technical Support and extremely long delays.

It has well over a month since I raised this Technical Support issue and yet still after all this time there is NO fix for this problem with the Adguard Filtering Lo

**Comment by piquark6046** [comment]
I think that integrating with AdGuard Assistant web browser extension and using `localStorage` (or `cookie`) API helps the issue to resolve.
