### ISSUE TITLE
`$replace` rules with escaped `$` don't work

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1846]
Rule: `wikipedia.org^$replace=/\$100/test/`
Link: https://en.m.wikipedia.org/wiki/United_States_one-hundred-dollar_bill

Checked in the latest AdGuards for Windows and Android, and in AdGuard for Android 3.7

**Comment by ngorskikh** [comment]
@Alex-302, the rule should look like this:
```
wikipedia.org^$replace=/\\$100/test/
```
1. You escape the `$` because it is reserved as a character that separates the modifiers from the pattern: `\$`.
2. Then you must escape the escaped `$` because it has a special meaning in a regular expression: `\\$`.
3. Note that `\\\$` would give incorrect results: `\` itself doesn't have to be escaped in our rule's syntax.

**Comment by ngorskikh** [comment]
@Alex-302 Update:
Although, we can probably reliably tell the `$` inside a regex apart from the `$` that's separating the pattern from the modifiers, so we can probably omit the requirement that a `$` must be escaped in a regex. This needs more testing, though. I'll get back to you on that.

**Comment by ngorskikh** [comment]
@Alex-302 
Unfortunately, on closer inspection, it doesn't look possible. Since a URI can include `$`, `=` and `=` without percent encoding (https://datatracker.ietf.org/doc/html/rfc3986#appendix-A), we take the last `$` not preceded by `\` as the pattern/modifiers separator. Thus, a `$` in a regex pattern in a rule must always be preceded by `\` in order to not be confused with the pattern/modifiers separator. So, my earlier comment stands: https://github.com/AdguardTeam/CoreLibs/issues/1846#issuecomment-1932079508

**Comment by Alex-302** [comment]
thanks
