### ISSUE TITLE
search.shopping.naver.com - does not open in the Firefox

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1873]
https://github.com/AdguardTeam/AdguardFilters/issues/176180 for some reason, the site does not open with the app in Firefox `124.0.1`.
To reproduce it:
1. Disable all the modules in the AdGuard for Windows
2. Enable global protection
3. Open the site from the report above in the Firefox `124.0.1` or other latest version
4. You will see the same error as in the first screenshot.

**Comment by sfionov** [comment]
@zloyden Do you use nightly or stable version?

**Comment by zloyden** [comment]
I use nightly `7.17.0 nightly 23`. @Alex-302 did check on the release version and had the same.

**Comment by k24u11** [comment]
Is there any update? I'm experiencing the same issue while using the 124.0.1 release version. The same problem persists in the 124.0.2 update version as well.

**Comment by ihurin** [comment]
Multiple users confirmed this issue.

**Comment by sfionov** [comment]
It was DDoS protection that triggered. The temporary workaround may be to add `search.shopping.naver.com` to HTTPS exclusions

**Comment by piquark6046** [comment]
Similar case (`smartstore.naver.com`) : https://github.com/AdguardTeam/AdguardFilters/issues/176863

It seems that only Firefox web browser with AdGuard CoreLib-based app is affected.

**Comment by piquark6046** [comment]
Similar case (`smartstore.naver.com`) : https://github.com/AdguardTeam/AdguardFilters/issues/176863

It seems that only Firefox web browser with AdGuard CoreLib-based app is affected.
I confirmed with Google Chrome web browser.

---

By the way, some Chromium users with a Nvidia GPU migrate to Firefox web browser because they encounter [a rendering issue](https://issues.chromium.org/issues/40735345).

**Comment by Morku** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1867

https://github.com/AdguardTeam/AdguardFilters/issues/182643
