### ISSUE TITLE
asusrouter.com cant be accessed with AdGuard running.

### ISSUE THREAD

**Issue by RtanieoL** [AdguardTeam/CoreLibs#1923]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

7.19.0

### Browser version

132.1

### OS version

Windows 11 Pro 23H2

### Issue Details

Steps to reproduce:
1. asusrouter.com
2.cant be accessed
3.with AdGuard running.
It doesnt matter what Browser.

### Actual Behavior

???

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by zzebrum** [comment]
In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://adguard.com/kb/adguard-for-windows/solving-problems/adguard-logs/).
2. Remember the exact time when the issue was reproduced.
3. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
		- include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
		- specify the exact time when the issue occurred

**Comment by zzebrum** [comment]
@RtanieoL any update?

**Comment by zzebrum** [comment]
Re-open if needed
