### ISSUE TITLE
Issues with Data Saver (Chrome Browser)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#412]
1. Start AdGuard
2. Open Chrome browser
3. Go to http://www.cbc.ca/
4. Try to play any audio/video content (internal player)

When you try to play any audio/video content with the internal player on cbc.ca it wouldn't load content. Data saver in Chrome browser is on.

**Comment by ameshkov** [comment]
On cbc only? What about other websites like Youtube?

**Comment by ameshkov** [comment]
Ah, this one is plain HTTP, that's the difference

**Comment by TheHasagi** [comment]
Youtube videos play fine, it's just what I found.

I can continue the research on this issue.

**Comment by szolin** [comment]
It turns out that when Data saver is on, videos don't load even if Adguard is not active.
The problem is due to the different video URLs that browser generates:

https://mobilehls-vh.akamaihd.net/i/prodVideo/.../master.m3u8?hdnea=ip=...

The end of the URL is different when Data saver is on.
With Data saver, akamaihd.net server just returns 403 error in response.
