### ISSUE TITLE
Move from hardcoded to external localizations in CoreLibs

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#447]
Error page, adblocked page, safebrowsing page must be localized from external source, not hardcoded as of now.

**Comment by TPS** [comment]
If the UI is localized internally now, why not do the same w/ those served pages?  It'd be faster for us users, & save on data.  If concerned about updating them, these could be added to https://github.com/AdguardTeam/AdguardForAndroid/issues/25 .…

**Comment by lancelot-moon** [comment]
@aalpatkina
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2sLADtU.png)
</details><br/>

It seems that the phrases for the warning of browsing security were uploaded to onesky, right?
In Adguard for Windows / Filtering Engine Str?

I had completed them.
You can apply them into the language file.

**Comment by ameshkov** [comment]
> It seems that the phrases for the warning of browsing security were uploaded to onesky, right?
In Adguard for Windows / Filtering Engine Str?

These are old ones, the proper strings are in `Miscellaneous`.

**Comment by lancelot-moon** [comment]
@ameshkov
All projects in Miscellaneous are also finished translating to Traditional Chinese.
Which project do you mean?
In Miscellaneous / Miscellaneous?
I remember that they're phrases for filters, not for the warning of browsing security...

By the way, translators reported mistakes on telegram, but nobody deals with the wrong/unsuitable phrases on onesky this week.
Are this week holidays in Russia?

**Comment by ameshkov** [comment]
> I remember that they're phrases for filters, not for the warning of browsing security...

There are, and all are translated already indeed.

> but nobody deals with the wrong/unsuitable phrases or questions on onesky this week

@aalpatkina has her hands full, please be patient.

**Comment by lancelot-moon** [comment]
@sfionov
@ameshkov 
@Revertron

Hi,
The warning of browsing security is still not localized with AG v3.0.242η.
It's English.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YduaswB.png)
</details><br/>

In AG Home, the warning of browsing security can be shown as Chinese Traditional according to my language setting.

But it's not fixed in AG for Android.

**Comment by lancelot-moon** [comment]
@ameshkov

May you reopen this since some languages' warning page of browsering security aren't localized?

We don't talk about the locales which have no translator.

The warning page has Japanese, German and other languages' page.

Why is it still English page for Chinese (zh-TW and zh-CN) and Portuguese (Portugal and Brazil)?
