### ISSUE TITLE
com.harmankaya.turkrapfm

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#461]
@adguard-bot commented on [Wed Aug 22 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21433)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.harmankaya.turkrapfm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.harmankaya.turkrapfm)
### Comment
> Adguard corelibs öncesi bu uygulama filtreleme açıkken sorunsuz çalışıyordu ama corelibs sonrası uygulama filtreleme açıkken çöküyor.. Bu konuda bir düzeltme talep ediyoruz... 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/I4M25w9.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.187β
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Mobile Ads,<br>Turkish,<br>Annoyances,<br>English,<br>Anti-Adblock Killer | Reek,<br>Spyware,<br>Social media

**Comment by sfionov** [comment]
Radios issues are already fixed in the latest nightly

**Comment by CronexTR** [comment]
Adguard aktif olduğunda uygulama sunucuya bağlanamıyor ve çöküyor, ama harici listeye aldığımda ise sorunsuz çalışıyor... 
-------- Orijinal mesaj --------Kimden: Sergey Fionov <notifications@github.com> Tarih: 03.09.2018  18:39  (GMT+03:00) Alıcı: AdguardTeam/CoreLibs <CoreLibs@noreply.github.com> Cc: CronexTR <selmantann@gmail.com>, Comment <comment@noreply.github.com> Konu: Re: [AdguardTeam/CoreLibs] com.harmankaya.turkrapfm (#461) 
Radios issues are already fixed in the latest nightly

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AdguardTeam/CoreLibs","title":"AdguardTeam/CoreLibs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AdguardTeam/CoreLibs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sfionov in #461: Radios issues are already fixed in the latest nightly"}],"action":{"name":"View Issue","url":"https://github.com/AdguardTeam/CoreLibs/issues/461#issuecomment-418147942"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AdguardTeam/CoreLibs/issues/461#issuecomment-418147942",
"url": "https://github.com/AdguardTeam/CoreLibs/issues/461#issuecomment-418147942",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [AdguardTeam/CoreLibs] com.harmankaya.turkrapfm (#461)",
"sections": [
{
"text": "",
"activityTitle": "**Sergey Fionov**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sfionov",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AdguardTeam/CoreLibs\",\n\"issueId\": 461,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"AdguardTeam/CoreLibs\",\n\"issueId\": 461\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/AdguardTeam/CoreLibs/issues/461#issuecomment-418147942"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 374747531\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sfionov** [comment]
Thanks for checking it!
