### ISSUE TITLE
AG4Win does not close some of the established TCP connections on protection reload

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#755]
Easy to reproduce on znaj.ua

**Comment by ameshkov** [comment]
Ok, not so fast, it's not that bad

**Comment by adbuker** [comment]
resolved in `core/pull-requests/1083`

**Comment by ameshkov** [comment]
@adbuker add testing instructions please

**Comment by adbuker** [comment]
how to test:
1. Close the Chrome browser
2. Start the latest version of AGW 
3. Start dumping the network  (follow instructions from chrome://net-export/)
4. Start e.g. `znaj.ua` in Chrome and walk through the sublinks
5. Disable AGW protection and wait until protection will be disabled completely
6. Stop dumping the network
7. Open the network dump in the "netlog-viewer "(https://chromium.googlesource.com/catapult/+/master/netlog_viewer/) and go to Sockets->View live sockets.

Expected behaviour: the list of live socket doesn't contain any sockets refer to the `znaj.ua`
