### ISSUE TITLE
Add debugging mode to CoreLibs (and to the content script)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#856]
It should be possible to enable so-called debugging mode in CoreLibs.

It is supposed to be enabled when the filtering log is active in the apps (or maybe we'll add an additional checkbox for enabling it).

This flag should be passed to the content script as well.

When it is enabled, here is what it should be printed to the console:
1. Indicate that debugging mode is enabled, and it might be heavy on CPU and memory
2. Scriptlets hits
3. ExtCSS rules hits
4. Other cosmetic rules hits

**Comment by adbuker** [comment]
Also within the resolving this issue, it'll be very useful to invoke BrowserApi events about applied rules with some unique uid (e.g. nonce). The "main" RequestProcessedEvent, related to processing this request, also should contain this uid. Then, after receiving both types of the events, then app can match RequestProcessedEvent with the collection of the Browser api events and provide the complete log record, which contains info about all applied cosmetic rules (instead of just flag `Cosmetic rule(s)` - as it described in https://github.com/AdguardTeam/CoreLibs/issues/858)
