### ISSUE TITLE
Unable to mask ipv6 address

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#938]
@anoop-b commented on [Sun May 12 2019](https://github.com/AdguardTeam/AdguardForMac/issues/488)

self explanatory.
- ipv4 masking works fine though.

**Comment by ameshkov** [comment]
Once it's done, we should create tasks in Win, Mac, and Android repos.

**Comment by sfionov** [comment]
So, we need custom IPv6 configuration option for IPv6 destination.

But my personal opinion is that, since this option become less and less reliable, and there is absolutely no guarantee that server will read such headers, it gives user dangerous illusion of imaginary security, comparing to VPNs. Why we continue to support this?

**Comment by vshlobinag** [comment]
Can't reproduce. Headers added to request in Windows, Android, macOS.
