### ISSUE TITLE
Broken web sites

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#951]
@adguard-bot commented on [Tue Jun 04 2019](https://github.com/AdguardTeam/AdguardFilters/issues/34738)

### Issue URL (Incorrect Blocking)
[http://www.jxzsey.com/Home/Apply](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.jxzsey.com%2FHome%2FApply)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AInKsd4.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/R7NcTjE.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.0.2693.6661
Browser: | Chrome
AdGuard driver: | WFP
Filters: | AdGuard Base,<br>AdGuard Tracking Protection,<br>EasyList China,<br>CJX's Annoyance List

---

@bogachenko commented on [Tue Jun 04 2019](https://github.com/AdguardTeam/AdguardFilters/issues/34738#issuecomment-498643543)

@ameshkov (репортил не я), взгляни на первый скриншот.
В основном я пользуюсь только расширением, но иногда включаю программу (нет скриплетов пока, поэтому сижу на 2 стульях. В дальнейшем откажусь от расширения в пользу программы). Так вот на некоторых сайтах (и даже на гитхаб, почему то только в разделах `issues` на разных репозиториях) я получаю аналогичный результат, как на 1 скрине. Дать тебе шаги для его воспроизведения я не могу, он появляется время от времени, не часто и только тогда, когда запущена программа. Это известный баг? Наверняка же репортили, да?

Пользуюсь Firefox, но как видно из этого репорта и на Chrome также проблема.
PS: Сайт, который дан в этом репорте отображается нормально. Пока что?

**Comment by Alex-302** [comment]
the same issue is on GitHub, when navigate through issues
![image](https://user-images.githubusercontent.com/8361299/58881301-96aa8800-86e2-11e9-81c5-f6a1af38e5d8.png)

**Comment by AdamWr** [comment]
One more reported website with similar issue - http://dushu.red/plugin.php?id=newtop_waterfall:newtop_waterfall
https://github.com/AdguardTeam/AdguardFilters/issues/34694

By the way, I can't reproduce it.

**Comment by AdamWr** [comment]
http://bbs.3dmgame.com/forum.php
https://github.com/AdguardTeam/AdguardFilters/issues/35018

**Comment by akmLaVx** [comment]
Additional logs have been submitted for this case: 1873446

**Comment by sfionov** [comment]
@planet0 reported in https://github.com/AdguardTeam/AdguardForMac/issues/544:







### Steps to reproduce

1. Visit https://github.com/AdguardTeam/AdguardHome/issues/
2. Click on an issue
3. Click on the 'Issues' tab
4. Repeat multiple times until behaviour

### Expected behavior
Browsing is as per usual

### Actual behavior

The webpage code is corrupted. Quit or disable AdGuard and issue won't occur.

<details><summary>Screenshot:</summary>


<img width="1552" alt="github" src="https://user-images.githubusercontent.com/46271764/60095217-6dd15c00-9791-11e9-806e-dfdc9f5b6c05.png">

</details>


### Your environment

* Environment name and version: (e.g. Chrome 59): Chrome Version 75.0.3770.90 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) AdGuard Home

**Comment by planet0** [comment]
Just clarifying that step 4 is to repeat steps 2 and 3, so you click on an issue, then go to Issues tab, click on an issue, go to Issues tab, etc.

Been able to replicate it often on the AdGuardHome Issues section only. Not sure why just there.

**Comment by sfionov** [comment]
Fixed in core/pull-requests/1348
